/**
 * Achievement seed data — 33 achievement definitions.
 *
 * Categories: time (8), progress (5), actions (5), challenges (3), collection (5), awareness (7)
 * 3 secret achievements (P009, A010, D006)
 * Condition types: streak_days, total_actions, specific_actions, milestones,
 *                  time_based, collection, cumulative_count, consecutive_days_bad
 */

export interface AchievementSeed {
  id: string;
  name: string;
  icon: string;
  category: string;
  difficulty: string;
  isSecret: boolean;
  description: string;
  conditionType: string;
  conditionValue: string;
}

export const ACHIEVEMENT_SEEDS: AchievementSeed[] = [
  // ── Time (streak-based) — 8 achievements ─────────────────────────
  {
    id: "T001",
    name: "Primera Semana",
    icon: "🔥",
    category: "time",
    difficulty: "easy",
    isSecret: false,
    description: "7 días sin fumar — ¡la primera semana completa!",
    conditionType: "streak_days",
    conditionValue: "7",
  },
  {
    id: "T002",
    name: "Dos Semanas",
    icon: "🌟",
    category: "time",
    difficulty: "easy",
    isSecret: false,
    description: "14 días de racha",
    conditionType: "streak_days",
    conditionValue: "14",
  },
  {
    id: "T003",
    name: "Tres Semanas",
    icon: "💪",
    category: "time",
    difficulty: "medium",
    isSecret: false,
    description: "21 días — el hábito se está formando",
    conditionType: "streak_days",
    conditionValue: "21",
  },
  {
    id: "T004",
    name: "Un Mes Limpio",
    icon: "🏆",
    category: "time",
    difficulty: "medium",
    isSecret: false,
    description: "30 días sin fumar — ¡un mes entero libre!",
    conditionType: "streak_days",
    conditionValue: "30",
  },
  {
    id: "T005",
    name: "Dos Meses",
    icon: "🎖️",
    category: "time",
    difficulty: "hard",
    isSecret: false,
    description: "60 días sin fumar",
    conditionType: "streak_days",
    conditionValue: "60",
  },
  {
    id: "T006",
    name: "Centenario",
    icon: "💎",
    category: "time",
    difficulty: "hard",
    isSecret: false,
    description: "100 días sin fumar — ¡un centurión!",
    conditionType: "streak_days",
    conditionValue: "100",
  },
  {
    id: "T007",
    name: "Seis Meses",
    icon: "👑",
    category: "time",
    difficulty: "hard",
    isSecret: false,
    description: "180 días — medio año de libertad",
    conditionType: "streak_days",
    conditionValue: "180",
  },
  {
    id: "T008",
    name: "Un Año",
    icon: "🏅",
    category: "time",
    difficulty: "extreme",
    isSecret: false,
    description: "365 días — ¡un año completo sin fumar!",
    conditionType: "streak_days",
    conditionValue: "365",
  },

  // ── Progress (milestones) — 5 achievements ───────────────────────
  {
    id: "P001",
    name: "Primer Cigarrillo Evitado",
    icon: "🚫",
    category: "progress",
    difficulty: "easy",
    isSecret: false,
    description: "Evitaste tu primer cigarrillo del día",
    conditionType: "milestones",
    conditionValue: "1",
  },
  {
    id: "P002",
    name: "Diez Vidas Ahorradas",
    icon: "❤️",
    category: "progress",
    difficulty: "easy",
    isSecret: false,
    description: "Ahorraste 10 vidas en total",
    conditionType: "milestones",
    conditionValue: "10",
  },
  {
    id: "P003",
    name: "Cincuenta Vidas",
    icon: "💚",
    category: "progress",
    difficulty: "medium",
    isSecret: false,
    description: "50 vidas ahorradas — ¡medio centenar!",
    conditionType: "milestones",
    conditionValue: "50",
  },
  {
    id: "P004",
    name: "Cien Vidas",
    icon: "💙",
    category: "progress",
    difficulty: "hard",
    isSecret: false,
    description: "100 vidas ahorradas — impacto real",
    conditionType: "milestones",
    conditionValue: "100",
  },
  {
    id: "P005",
    name: "Cincocientas Vidas",
    icon: "💜",
    category: "progress",
    difficulty: "extreme",
    isSecret: false,
    description: "500 vidas ahorradas — ¡leyenda!",
    conditionType: "milestones",
    conditionValue: "500",
  },

  // ── Actions (positive actions) — 5 achievements ──────────────────
  {
    id: "A001",
    name: "Primera Acción Positiva",
    icon: "🎯",
    category: "actions",
    difficulty: "easy",
    isSecret: false,
    description: "Realizaste tu primera acción positiva",
    conditionType: "total_actions",
    conditionValue: "1",
  },
  {
    id: "A002",
    name: "Diez Acciones",
    icon: "📝",
    category: "actions",
    difficulty: "easy",
    isSecret: false,
    description: "10 acciones positivas completadas",
    conditionType: "total_actions",
    conditionValue: "10",
  },
  {
    id: "A003",
    name: "Cincuenta Acciones",
    icon: "🔥",
    category: "actions",
    difficulty: "medium",
    isSecret: false,
    description: "50 acciones positivas — ¡constancia!",
    conditionType: "total_actions",
    conditionValue: "50",
  },
  {
    id: "A004",
    name: "Cien Acciones",
    icon: "💫",
    category: "actions",
    difficulty: "hard",
    isSecret: false,
    description: "100 acciones positivas — ¡máquina de progreso!",
    conditionType: "total_actions",
    conditionValue: "100",
  },
  {
    id: "A005",
    name: "Acción Secreta",
    icon: "🔮",
    category: "actions",
    difficulty: "extreme",
    isSecret: true,
    description: "Completa una acción exactamente a medianoche",
    conditionType: "specific_actions",
    conditionValue: "midnight",
  },

  // ── Challenges (difficulty/time-based) — 3 achievements ──────────
  {
    id: "D001",
    name: "Desafío del Día",
    icon: "⚔️",
    category: "challenges",
    difficulty: "easy",
    isSecret: false,
    description: "Completa tu primer desafío diario",
    conditionType: "milestones",
    conditionValue: "1",
  },
  {
    id: "D002",
    name: "Semana de Desafíos",
    icon: "🛡️",
    category: "challenges",
    difficulty: "medium",
    isSecret: false,
    description: "Completa desafíos por 7 días seguidos",
    conditionType: "streak_days",
    conditionValue: "7",
  },
  {
    id: "D003",
    name: "El Desafiante Secreto",
    icon: "🤫",
    category: "challenges",
    difficulty: "extreme",
    isSecret: true,
    description: "Completa 50 desafíos en total",
    conditionType: "total_actions",
    conditionValue: "50",
  },

  // ── Collection (category completion) — 5 achievements ────────────
  {
    id: "C001",
    name: "Cronómetro",
    icon: "⏱️",
    category: "collection",
    difficulty: "hard",
    isSecret: false,
    description: "Desbloquea todas las insignias de la categoría Tiempo",
    conditionType: "collection",
    conditionValue: "time",
  },
  {
    id: "C002",
    name: "Constructor de Progreso",
    icon: "🏗️",
    category: "collection",
    difficulty: "hard",
    isSecret: false,
    description: "Desbloquea todas las insignias de la categoría Progreso",
    conditionType: "collection",
    conditionValue: "progress",
  },
  {
    id: "C003",
    name: "Maestro de Acciones",
    icon: "🎭",
    category: "collection",
    difficulty: "hard",
    isSecret: false,
    description: "Desbloquea todas las insignias de la categoría Acciones",
    conditionType: "collection",
    conditionValue: "actions",
  },
  {
    id: "C004",
    name: "Conquistador de Desafíos",
    icon: "🗡️",
    category: "collection",
    difficulty: "extreme",
    isSecret: false,
    description: "Desbloquea todas las insignias de la categoría Desafíos",
    conditionType: "collection",
    conditionValue: "challenges",
  },
  {
    id: "C005",
    name: "La Estrella Oculta",
    icon: "🌟",
    category: "collection",
    difficulty: "extreme",
    isSecret: true,
    description: "Desbloquea todas las insignias del juego",
    conditionType: "collection",
    conditionValue: "all",
  },

  // ── Bad awareness (cumulative smoking) — 7 achievements ──────────
  {
    id: "B001",
    name: "Primer Cigarrillo Registrado",
    icon: "🚬",
    category: "awareness",
    difficulty: "easy",
    isSecret: false,
    description: "Registraste tu primer cigarrillo — el primer paso es ser consciente",
    conditionType: "cumulative_count",
    conditionValue: "1",
  },
  {
    id: "B002",
    name: "Diez Cigarrillos",
    icon: "📊",
    category: "awareness",
    difficulty: "easy",
    isSecret: false,
    description: "10 cigarrillos registrados — cada uno cuenta",
    conditionType: "cumulative_count",
    conditionValue: "10",
  },
  {
    id: "B003",
    name: "Cincuenta Cigarrillos",
    icon: "📈",
    category: "awareness",
    difficulty: "medium",
    isSecret: false,
    description: "50 cigarrillos registrados — ¿cuántos más?",
    conditionType: "cumulative_count",
    conditionValue: "50",
  },
  {
    id: "B004",
    name: "Cien Cigarrillos",
    icon: "📉",
    category: "awareness",
    difficulty: "hard",
    isSecret: false,
    description: "100 cigarrillos registrados — el impacto es real",
    conditionType: "cumulative_count",
    conditionValue: "100",
  },
  {
    id: "B005",
    name: "Racha de Tabaquismo",
    icon: "⚠️",
    category: "awareness",
    difficulty: "medium",
    isSecret: false,
    description: "3 días consecutivos fumando — time to change",
    conditionType: "consecutive_days_bad",
    conditionValue: "3",
  },
  {
    id: "B006",
    name: "Semana Fumando",
    icon: "🚨",
    category: "awareness",
    difficulty: "hard",
    isSecret: false,
    description: "7 días consecutivos fumando — considera buscar ayuda",
    conditionType: "consecutive_days_bad",
    conditionValue: "7",
  },
  {
    id: "B007",
    name: "Mes de Tabaquismo",
    icon: "🛑",
    category: "awareness",
    difficulty: "extreme",
    isSecret: false,
    description: "30 días consecutivos fumando — cada cigarrillo cuenta, empieza hoy",
    conditionType: "consecutive_days_bad",
    conditionValue: "30",
  },
];

/** Total number of achievements */
export const ACHIEVEMENT_COUNT = ACHIEVEMENT_SEEDS.length; // 33
